site_name: AlyxLib
site_url: https://github.com/FrostSource/alyxlib
site_dir: site # Change on release

repo_url: https://github.com/FrostSource/alyxlib
repo_name: FrostSource/alyxlib

theme:
  logo: assets/alyxlib_logo-white.svg
  favicon: assets/alyxlib_logo-white.svg
  
  name: material
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: cyan
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: cyan
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: cyan
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    # - navigation.prune # Only if docs get big
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.sections

nav:
  - Home: index.md
  - Getting Started:
    - App Installation: getting_started/app_installation.md
    - Python Installation: getting_started/python_installation.md
    - Manual Installation: getting_started/manual_installation.md
    - Developing: getting_started/developing.md
    - Uploading to the workshop: getting_started/uploading_to_workshop.md
  - Components:
    # - components/index.md
    - AlyxLib: components/alyxlib.md
    - Player: components/player.md
    - Debug Menu: components/debug_menu.md
    - Entity Classes: components/classes.md
    - Input: components/input.md
    - Storage: components/storage.md
    - Panorama: components/panorama.md
    - Global Precache: components/global_precache.md
    - Debugging: components/debugging.md
    # - Hammer Exposed: components/exposed.md
    - Entity Mods:
      - components/entity_mods/index.md
      - trigger_look_arbitrary: components/entity_mods/trigger_look_arbitrary.md
  - Console:
    - console/index.md
    - AlyxLib Commands: console/alyxlib.md
    - Common Commands: console/common.md
    - VR Commands: console/vr.md
    - NoVR Commands: console/novr.md
    - Debug Menu: console/debug_menu.md
  - Addons: addons.md
  - Reference:
    - Class: reference/class.md
    - Globals: reference/globals.md
    - Precache: reference/precache.md
    - Storage: reference/storage.md
    - Controls:
      - Gesture: reference/controls/gesture.md
      - Haptics: reference/controls/haptics.md
      - Input: reference/controls/input.md
    - Data:
      - Color: reference/data/color.md
      - Inventory: reference/data/inventory.md
      - Queue: reference/data/queue.md
      - Stack: reference/data/stack.md
    - Debug:
      - Commands: reference/debug/commands.md
      - Common: reference/debug/common.md
      - Debug Menu: reference/debug/debug_menu.md
      - NoVR: reference/debug/novr.md
      - Profiling: reference/debug/profiling.md
    - Extensions:
      - Entities: reference/extensions/entities.md
      - Entity: reference/extensions/entity.md
      - NPC: reference/extensions/npc.md
      - String: reference/extensions/string.md
      - Template: reference/extensions/template.md
      - Vector: reference/extensions/vector.md
    - Helpers:
      - Animation: reference/helpers/animation.md
      - EasyConvars: reference/helpers/easyconvars.md
    - Math:
      - Common: reference/math/common.md
      - OBB: reference/math/obb.md
      - Weighted Random: reference/math/weighted_random.md
    - Panorama:
      - Core: reference/panorama/core.md
    - Player:
      - Core: reference/player/core.md
      - Data: reference/player/data.md
      - Events: reference/player/events.md
      - Hands: reference/player/hands.md
      - Wrist Attachments: reference/player/wrist_attachments.md
    - Utils:
      - Common: reference/utils/common.md

plugins:
  - offline
  - search
  - privacy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.tilde
  - tables
  - def_list

  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  - admonition
  - pymdownx.details

extra_css:
  - stylesheets/exposed.css
  - stylesheets/alyxlib.css

