name: Check Lua Version Bumps

on:
  pull_request:
    branches: [ actions_test ]

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for diffing

      - name: Check if modified .lua files have version updated
        run: |
          git fetch origin main
          CHANGED_LUA=$(git diff --name-only origin/main...HEAD -- '*.lua')
          ERROR_FILES=""

          for file in $CHANGED_LUA; do
            # Extract version line from the first few lines of the old and new file
            OLD_VERSION=$(git show origin/main:$file | head -n 10 | grep -oP 'v\d+\.\d+\.\d+' || true)
            NEW_VERSION=$(head -n 10 "$file" | grep -oP 'v\d+\.\d+\.\d+' || true)

            if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
              ERROR_FILES="$ERROR_FILES\n- $file (version not updated, still $NEW_VERSION)"
            fi
          done

          if [ -n "$ERROR_FILES" ]; then
            echo -e "❌ The following Lua files were modified, but their version comments were not updated:$ERROR_FILES"
            echo "Please update the version (e.g., v2.1.1) in the top comment block of each changed file."
            echo "Showing diffs for changed Lua files:\n"
            for file in $CHANGED_LUA; do
              echo "=== Diff for $file ==="
              git --no-pager diff origin/main...HEAD -- "$file"
              echo ""
            done
            exit 1
          else
            echo "✅ All modified Lua files have updated version comments."
          fi
